/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prog_cafe_g3;

import java.util.Arrays;
import java.util.List;
import javax.swing.JCheckBox;

/**
 *
 * @author fshaik
 */
public class Prog_Cafe_Order_Form extends javax.swing.JFrame {

    /**
     * Creates new form Prog_Cafe_Order_Form
     */
    public Prog_Cafe_Order_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        title_Label = new javax.swing.JLabel();
        mainIngredient_Label = new javax.swing.JLabel();
        mainIngredient_ComboBox = new javax.swing.JComboBox<>();
        bread_Label = new javax.swing.JLabel();
        bread_ComboBox = new javax.swing.JComboBox<>();
        toppings_Label = new javax.swing.JLabel();
        lettuce_CheckBox1 = new javax.swing.JCheckBox();
        cheese_CheckBox2 = new javax.swing.JCheckBox();
        tomatoe_CheckBox3 = new javax.swing.JCheckBox();
        onions_CheckBox4 = new javax.swing.JCheckBox();
        bellPeppers_CheckBox5 = new javax.swing.JCheckBox();
        toastedChoice_Label = new javax.swing.JLabel();
        toasted_RadioButton1 = new javax.swing.JRadioButton();
        nonToasted_RadioButton2 = new javax.swing.JRadioButton();
        specialInstructions_Label = new javax.swing.JLabel();
        specialInstructions_ScrollPane1 = new javax.swing.JScrollPane();
        specialInstructions_TextArea1 = new javax.swing.JTextArea();
        orderSummary_Label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderSummary_List1 = new javax.swing.JList<>();
        orderSummary_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title_Label.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        title_Label.setForeground(new java.awt.Color(51, 204, 255));
        title_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_Label.setText("Prog Cafe Sandwich Order Form");
        title_Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 51)));

        mainIngredient_Label.setText("Main Ingredient Choice: ");

        mainIngredient_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beef", "Chicken", "Tuna", "Turkey", "Veggie Patty" }));

        bread_Label.setText("Bread Choice: ");

        bread_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "White Bread", "Whole-Wheat Bread", "Rye Bread", "Italian Bread", "Gluten-Free Bread" }));

        toppings_Label.setText("Toppings:");

        lettuce_CheckBox1.setText("Lettuce");

        cheese_CheckBox2.setText("Cheese");

        tomatoe_CheckBox3.setText("Tomatoe");

        onions_CheckBox4.setText("Onions");

        bellPeppers_CheckBox5.setText("Bell Peppers");

        toastedChoice_Label.setText("Toasted:");

        buttonGroup1.add(toasted_RadioButton1);
        toasted_RadioButton1.setText("Toasted");

        buttonGroup1.add(nonToasted_RadioButton2);
        nonToasted_RadioButton2.setText("Non-Toasted");

        specialInstructions_Label.setText("Special Instructions:");

        specialInstructions_TextArea1.setColumns(20);
        specialInstructions_TextArea1.setRows(5);
        specialInstructions_ScrollPane1.setViewportView(specialInstructions_TextArea1);

        orderSummary_Label.setText("Order Summary: ");

        jScrollPane1.setViewportView(orderSummary_List1);

        orderSummary_Button.setText("Display Order Summary");
        orderSummary_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderSummary_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(title_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mainIngredient_Label)
                                .addGap(18, 18, 18)
                                .addComponent(mainIngredient_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97)
                                .addComponent(bread_Label)
                                .addGap(18, 18, 18)
                                .addComponent(bread_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(toppings_Label)
                                    .addComponent(toastedChoice_Label))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(toasted_RadioButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(nonToasted_RadioButton2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lettuce_CheckBox1)
                                        .addGap(18, 18, 18)
                                        .addComponent(cheese_CheckBox2)
                                        .addGap(18, 18, 18)
                                        .addComponent(tomatoe_CheckBox3)
                                        .addGap(18, 18, 18)
                                        .addComponent(onions_CheckBox4)
                                        .addGap(18, 18, 18)
                                        .addComponent(bellPeppers_CheckBox5))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(specialInstructions_Label)
                                    .addComponent(orderSummary_Label))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(specialInstructions_ScrollPane1)
                                    .addComponent(jScrollPane1))))
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(orderSummary_Button)
                        .addGap(334, 334, 334))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainIngredient_Label)
                    .addComponent(mainIngredient_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bread_Label)
                    .addComponent(bread_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cheese_CheckBox2)
                    .addComponent(tomatoe_CheckBox3)
                    .addComponent(onions_CheckBox4)
                    .addComponent(bellPeppers_CheckBox5)
                    .addComponent(lettuce_CheckBox1)
                    .addComponent(toppings_Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toastedChoice_Label)
                    .addComponent(toasted_RadioButton1)
                    .addComponent(nonToasted_RadioButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(specialInstructions_ScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(specialInstructions_Label)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(orderSummary_Label))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(orderSummary_Button)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orderSummary_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderSummary_ButtonActionPerformed
        //Create a string builder for the order summary
        StringBuilder orderSummary = new StringBuilder();
        //get the selected main ingredient
        orderSummary.append("Main Ingredient: ").append(mainIngredient_ComboBox.getSelectedItem()).append("\n");
        //get the selected bread choice
        orderSummary.append("Bread Choice: ").append(bread_ComboBox.getSelectedItem()).append("\n");
        //Simplified toppings selection using an array of checkboxes & their corresponding names
        JCheckBox[] checkboxes ={lettuce_CheckBox1,cheese_CheckBox2,tomatoe_CheckBox3,onions_CheckBox4,bellPeppers_CheckBox5};
        String [] toppingsNames = {"Lettuce", "Cheese", "Tomatoe", "Onions", "Bell Peppers" };
                StringBuilder toppings = new StringBuilder ("Toppings: ");
                for(int i = 0; i < checkboxes.length; i++){
                        if(checkboxes[i].isSelected()){
                            toppings.append(toppingsNames[i]).append(" , ");
                        }
                }
                //Remove the trailing comma & empty spaces (non-selected items) if present
                if(toppings.charAt(toppings.length() -2 ) ==  ',') {
                                toppings.delete(toppings.length() - 2, toppings.length());
                }
                toppings.append("\n");
                //Append the toppings to the main summary
                orderSummary.append(toppings);
                
                //Get toasted choice
                if(toasted_RadioButton1.isSelected())
                {
                    orderSummary.append("Toasted Choice: Toasted\n");
                } else if (nonToasted_RadioButton2.isSelected())
                {
                    orderSummary.append("Toasted Choice: Non-Toasted\n");
                }
                
                //Get special instructions text if any posted in the text area
                if(!specialInstructions_TextArea1.getText().trim().isEmpty()){
                        orderSummary.append("Special Instructions: ").append(specialInstructions_TextArea1.getText().trim()).append("\n");
                }
                
                //Convert the StringBuilder to a List of Strings, with each string as a line List<String> (each order component will be a line item)
                  List<String> lines;
                 lines = Arrays.asList(orderSummary.toString().split("\n"));
                orderSummary_List1.setListData(lines.toArray(new String[0]));  
    }//GEN-LAST:event_orderSummary_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prog_Cafe_Order_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prog_Cafe_Order_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prog_Cafe_Order_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prog_Cafe_Order_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prog_Cafe_Order_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bellPeppers_CheckBox5;
    private javax.swing.JComboBox<String> bread_ComboBox;
    private javax.swing.JLabel bread_Label;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cheese_CheckBox2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox lettuce_CheckBox1;
    private javax.swing.JComboBox<String> mainIngredient_ComboBox;
    private javax.swing.JLabel mainIngredient_Label;
    private javax.swing.JRadioButton nonToasted_RadioButton2;
    private javax.swing.JCheckBox onions_CheckBox4;
    private javax.swing.JButton orderSummary_Button;
    private javax.swing.JLabel orderSummary_Label;
    private javax.swing.JList<String> orderSummary_List1;
    private javax.swing.JLabel specialInstructions_Label;
    private javax.swing.JScrollPane specialInstructions_ScrollPane1;
    private javax.swing.JTextArea specialInstructions_TextArea1;
    private javax.swing.JLabel title_Label;
    private javax.swing.JLabel toastedChoice_Label;
    private javax.swing.JRadioButton toasted_RadioButton1;
    private javax.swing.JCheckBox tomatoe_CheckBox3;
    private javax.swing.JLabel toppings_Label;
    // End of variables declaration//GEN-END:variables
}
