/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musiclessons_gui;

import javax.swing.JOptionPane;

/**
 *
 * @author fshaik
 */
public class Music_GUI extends javax.swing.JFrame {
    int [][] prices = {
                                {150, 250, 280},
                                {215,232,280},
                                {130,185,310}
                                };
    String [] instrument = {"Guitar", "Piano", "Violin"};
    String [] level = {"Beginner", "Intermediate", "Advance"};
    
    
    public Music_GUI() {
        initComponents();
        PopulateInstrument();
        PopulateLevel();
    }

                private void PopulateInstrument(){
                        for(int x = 0; x<3;x++){
                                instrutmentComboBox.addItem(instrument[x]);
                        }
                
                }
                
                 private void PopulateLevel(){
                        for(int x = 0; x<3;x++){
                                levelComboBox.addItem(level[x]);
                        }
                }
                 
                 
                 private void Submit(){
                        try{
                                        int selected_platform = this.instrutmentComboBox.getSelectedIndex();
                                        int selected_level = this.levelComboBox.getSelectedIndex();
                                        
                                        JOptionPane.showMessageDialog(null, "Instrument: " + instrument[selected_platform] + 
                                                    "\nLevel: " + level[selected_level] +
                                                "\nPrice: R " + prices[selected_platform][selected_level], "Music Lessons Prices",
                                                JOptionPane.INFORMATION_MESSAGE);
                                        
                        }
                        catch(ArrayIndexOutOfBoundsException arrayError){
                                    JOptionPane.showMessageDialog(null, "Please select both instrument & level!!!");
                        }
                        catch(Exception ex){
                            System.out.println("The following error occured: " + ex.toString());
                        }
                 }
                 
                 private void Report(){
                 try{
                            String display_report = "";
                            for(int x = 0; x< prices.length; x++)
                            {
                                int sum = 0;
                                
                                        for(int y=0; y< prices[x].length; y++)
                                        {
                                                sum +=prices[x][y];
                                        }
                                            display_report +=   "Average lesson price for " + level[x] + " : R " +(sum/3) + "\n";
                            }
                                    JOptionPane.showMessageDialog(null, display_report);                 
                 }
                 catch(Exception ex){
                        ex.printStackTrace();
                 }
                 }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        instrutmentComboBox = new javax.swing.JComboBox<>();
        levelComboBox = new javax.swing.JComboBox<>();
        submitButton = new javax.swing.JButton();
        reportButton = new javax.swing.JButton();
        menubar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        toolsMenu = new javax.swing.JMenu();
        submitMenu = new javax.swing.JMenuItem();
        reportMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Music Lessons");

        jLabel1.setText("INSTRUMENT:");

        jLabel2.setText("LEVEL:");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        reportButton.setText("Report");
        reportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportButtonActionPerformed(evt);
            }
        });

        fileMenu.setText("File");
        menubar.add(fileMenu);

        toolsMenu.setText("Tools");
        toolsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolsMenuActionPerformed(evt);
            }
        });

        submitMenu.setText("Submit");
        submitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitMenuActionPerformed(evt);
            }
        });
        toolsMenu.add(submitMenu);

        reportMenu.setText("Report");
        reportMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportMenuActionPerformed(evt);
            }
        });
        toolsMenu.add(reportMenu);

        menubar.add(toolsMenu);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(submitButton)
                        .addGap(126, 126, 126)
                        .addComponent(reportButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(levelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(66, 66, 66)
                            .addComponent(instrutmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(instrutmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(levelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(reportButton))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
      Submit();
    }//GEN-LAST:event_submitButtonActionPerformed

    private void reportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportButtonActionPerformed
      Report();
    }//GEN-LAST:event_reportButtonActionPerformed

    private void toolsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolsMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toolsMenuActionPerformed

    private void submitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitMenuActionPerformed
        Submit();
    }//GEN-LAST:event_submitMenuActionPerformed

    private void reportMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportMenuActionPerformed
      Report();
    }//GEN-LAST:event_reportMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Music_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Music_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Music_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Music_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Music_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu fileMenu;
    private javax.swing.JComboBox<String> instrutmentComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> levelComboBox;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JButton reportButton;
    private javax.swing.JMenuItem reportMenu;
    private javax.swing.JButton submitButton;
    private javax.swing.JMenuItem submitMenu;
    private javax.swing.JMenu toolsMenu;
    // End of variables declaration//GEN-END:variables
}
