/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petrol_application_gui;

import java.text.DecimalFormat;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author fshaik
 */
public class Petrol_Application extends javax.swing.JFrame {
// Define arrays to hold the city names and their corresponding petrol prices for each year
    private static final String[] CITIES = { "Johannesburg", "Durban", "Cape Town" };
    private static final String[] YEARS = { "2017", "2018", "2019" };

    private static final double[][] PETROL_PRICES = {
        {10.72, 10.35, 10.20}, // Prices for Johannesburg for 2017, 2018, 2019
        {12.75, 12.32, 12.22}, // Prices for Durban for 2017, 2018, 2019
        {13.70, 13.31, 13.23}  // Prices for Cape Town for 2017, 2018, 2019
    };

    private final DecimalFormat df = new DecimalFormat("#.##");
        
    public Petrol_Application() {
        initComponents();
    }
    private void showPetrolPrice(){
        String selectedCity = city_List.getSelectedValue();
        String selectedYear = (String)year_ComboBox.getSelectedItem();
        String msg = "City: " + selectedCity + "\nYear: " + selectedYear + "\nCost: R";
        
        int cityIndex = Arrays.asList(CITIES).indexOf(selectedCity);
        int yearIndex = Arrays.asList(YEARS).indexOf(selectedYear);
        
        if(cityIndex != -1 && yearIndex != -1) {
            msg += df.format(PETROL_PRICES[cityIndex][yearIndex]);
        } else {
            msg = "No data available for selected city & year";
        }
        
        JOptionPane.showMessageDialog(null, msg);
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        city_Label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        city_List = new javax.swing.JList<>();
        year_Label = new javax.swing.JLabel();
        year_ComboBox = new javax.swing.JComboBox<>();
        submit_Button = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        file_Menu = new javax.swing.JMenu();
        exit_MenuItem = new javax.swing.JMenuItem();
        tools_Menu = new javax.swing.JMenu();
        submit_MenuItem = new javax.swing.JMenuItem();
        report_MenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Petrol Application GUI");

        city_Label.setText("City:");

        city_List.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Johannesburg", "Durban", "Cape Town" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(city_List);

        year_Label.setText("Year:");

        year_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019" }));

        submit_Button.setText("Submit");
        submit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_ButtonActionPerformed(evt);
            }
        });

        file_Menu.setText("File");

        exit_MenuItem.setText("Exit");
        exit_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_MenuItemActionPerformed(evt);
            }
        });
        file_Menu.add(exit_MenuItem);

        jMenuBar1.add(file_Menu);

        tools_Menu.setText("Tools");

        submit_MenuItem.setText("Submit");
        submit_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_MenuItemActionPerformed(evt);
            }
        });
        tools_Menu.add(submit_MenuItem);

        report_MenuItem.setText("Report");
        report_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report_MenuItemActionPerformed(evt);
            }
        });
        tools_Menu.add(report_MenuItem);

        jMenuBar1.add(tools_Menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(year_Label)
                                .addGap(18, 18, 18)
                                .addComponent(year_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(city_Label)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(submit_Button)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(city_Label))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(year_Label)
                    .addComponent(year_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(submit_Button)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_ButtonActionPerformed
       showPetrolPrice();
    }//GEN-LAST:event_submit_ButtonActionPerformed

    private void submit_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_MenuItemActionPerformed
       showPetrolPrice();
    }//GEN-LAST:event_submit_MenuItemActionPerformed

    private void exit_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_MenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exit_MenuItemActionPerformed

    private void report_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report_MenuItemActionPerformed
String msg;
    double[] averages = new double[CITIES.length];
    
    for (int cityIndex = 0; cityIndex < CITIES.length; cityIndex++) {
        double sum = 0;
        for (int yearIndex = 0; yearIndex < YEARS.length; yearIndex++) {
            sum += PETROL_PRICES[cityIndex][yearIndex];
        }
        averages[cityIndex] = sum / YEARS.length;
    }
    
    msg = "Average Petrol Cost for " + CITIES[0] + " is R " + df.format(averages[0]) + "\n"
        + "Average Petrol Cost for " + CITIES[1] + " is R " + df.format(averages[1]) + "\n"
        + "Average Petrol Cost for " + CITIES[2] + " is R " + df.format(averages[2]);
    
    JOptionPane.showMessageDialog(null, msg);

    }//GEN-LAST:event_report_MenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Petrol_Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Petrol_Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Petrol_Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Petrol_Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Petrol_Application().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel city_Label;
    private javax.swing.JList<String> city_List;
    private javax.swing.JMenuItem exit_MenuItem;
    private javax.swing.JMenu file_Menu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem report_MenuItem;
    private javax.swing.JButton submit_Button;
    private javax.swing.JMenuItem submit_MenuItem;
    private javax.swing.JMenu tools_Menu;
    private javax.swing.JComboBox<String> year_ComboBox;
    private javax.swing.JLabel year_Label;
    // End of variables declaration//GEN-END:variables
}
