/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petrol_application_g1;

import java.text.DecimalFormat;
import java.util.Arrays;
import javax.swing.JOptionPane;

public class Petrol_App_GUI extends javax.swing.JFrame {
    //define the arrays to hold the city & year data
    private static final String [] CITIES = {"Johannesburg", "Durban", "Cape Town"};
    private static final String [] YEAR = {"2017", "2018", "2019"}; 
    
    private static final double [][] PETROL_PRICES = {
        {10.72, 10.35, 10.20},//Prices for Johannesburg for 2017-2019
        {12.75, 12.32,12.22},//Prices for Durban for 2017-2019  
        {13.70,13.31, 13.23},//Prices for Cape-Town for 2017-2019
    };
    
    private final DecimalFormat df = new DecimalFormat("#.##");

    /**
     * Creates new form Petrol_App_GUI
     */
    public Petrol_App_GUI() {
        initComponents();
    }
    
    private void showPetrolPrice(){
    //In this method we will define the logic for the submit option
    //User selection for city & year will render a JOption show message dialog box with the correct petrol price
    
    String selectedCity = city_List.getSelectedValue();
    String selectedYear = (String)year_ComboBox.getSelectedItem();
    String msg = "City: " + selectedCity + "\nYear: " + selectedYear + "\nCost: R";
    
    int cityIndex = Arrays.asList(CITIES).indexOf(selectedCity);
    int yearIndex = Arrays.asList(YEAR).indexOf(selectedYear);
    
    if(cityIndex !=-1 && yearIndex !=-1){
        msg += df.format(PETROL_PRICES[cityIndex][yearIndex]);
    } else {
            msg = "No data was found based on your selection for city & year ";
    }
    
        JOptionPane.showMessageDialog(null, msg);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        city_Label = new javax.swing.JLabel();
        year_Label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        city_List = new javax.swing.JList<>();
        year_ComboBox = new javax.swing.JComboBox<>();
        submit_Button = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        file_MenuItem = new javax.swing.JMenu();
        exit_MenuItem = new javax.swing.JMenuItem();
        tools_MenuItem = new javax.swing.JMenu();
        submit_MenuItem = new javax.swing.JMenuItem();
        report_MenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Petrol Application - GUI");

        city_Label.setText("City:");

        year_Label.setText("Year:");

        city_List.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Johannesburg", "Durban", "Cape Town" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(city_List);

        year_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019" }));

        submit_Button.setText("Submit");
        submit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_ButtonActionPerformed(evt);
            }
        });

        file_MenuItem.setText("File");

        exit_MenuItem.setText("Exit");
        exit_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_MenuItemActionPerformed(evt);
            }
        });
        file_MenuItem.add(exit_MenuItem);

        MenuBar.add(file_MenuItem);

        tools_MenuItem.setText("Tools");

        submit_MenuItem.setText("Submit");
        submit_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_MenuItemActionPerformed(evt);
            }
        });
        tools_MenuItem.add(submit_MenuItem);

        report_MenuItem.setText("Report");
        report_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report_MenuItemActionPerformed(evt);
            }
        });
        tools_MenuItem.add(report_MenuItem);

        MenuBar.add(tools_MenuItem);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(year_Label)
                                .addGap(18, 18, 18)
                                .addComponent(year_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(city_Label)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(submit_Button)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(city_Label)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(year_Label)
                    .addComponent(year_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(submit_Button)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_MenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exit_MenuItemActionPerformed

    private void submit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_ButtonActionPerformed
        showPetrolPrice();
    }//GEN-LAST:event_submit_ButtonActionPerformed

    private void submit_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_MenuItemActionPerformed
         showPetrolPrice();
    }//GEN-LAST:event_submit_MenuItemActionPerformed

    private void report_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report_MenuItemActionPerformed
        double [] averages = new double[CITIES.length];
        
        for(int cityIndex = 0; cityIndex <CITIES.length; cityIndex++){
            double sum =0;
            for(int yearIndex =0; yearIndex <YEAR.length; yearIndex++){
                        sum +=PETROL_PRICES[cityIndex][yearIndex];
            }
        
                averages[cityIndex] = sum /YEAR.length;
        }
            String msg = "Avearge Petrol Cost for " + CITIES[0] + " is R " + df.format(averages[0]) + "\n" +
                                        "Avearge Petrol Cost for " + CITIES[1] + " is R " + df.format(averages[1]) + "\n"+
                                         "Avearge Petrol Cost for " + CITIES[2] + " is R " + df.format(averages[2]);       
          
            JOptionPane.showMessageDialog(null, msg);
    }//GEN-LAST:event_report_MenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Petrol_App_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Petrol_App_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Petrol_App_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Petrol_App_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Petrol_App_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JLabel city_Label;
    private javax.swing.JList<String> city_List;
    private javax.swing.JMenuItem exit_MenuItem;
    private javax.swing.JMenu file_MenuItem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem report_MenuItem;
    private javax.swing.JButton submit_Button;
    private javax.swing.JMenuItem submit_MenuItem;
    private javax.swing.JMenu tools_MenuItem;
    private javax.swing.JComboBox<String> year_ComboBox;
    private javax.swing.JLabel year_Label;
    // End of variables declaration//GEN-END:variables
}
