/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital_inspections_gui;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * 
 */
public class Hospital_GUI_App extends javax.swing.JFrame {

    //Max 5 inspections 
    String [][] inspections = new String [5][3];
    int inspectionCount = 0; //keeps track of the number of Inspections
    
    
    public Hospital_GUI_App() {
        initComponents();
    }
    
    DefaultListModel createReport(String name, String location, String years, DefaultListModel report){
            report.addElement("Hospital Name: " + name);
            report.addElement("Hospital Location: " + location);
            report.addElement("Years since inspections: " + years + " years ");
            report.addElement("*****************************************");
    return report;
    }
    
    private void Save(){
        if(inspectionCount !=5){
                 String name = this.name_TextField.getText();
                 String location = this.location_TextField.getText();
                 int years = this.year_ComboBox.getSelectedIndex() + 1; 
                 
                 inspections[inspectionCount][0] = name;
                 inspections[inspectionCount][1] = location;
                 inspections[inspectionCount][2] = " " + years;
                 inspectionCount +=1;
                 
                 this.name_TextField.setText("");
                 this.location_TextField.setText("");
        }else
            {JOptionPane.showMessageDialog(null, "Maximum number of inspections count has been reached");}
    }
    
    private void Clear(){
        this.name_TextField.setText("");
        this.location_TextField.setText("");
        DefaultListModel report = new DefaultListModel();
        this.details_List.setModel(report);
        inspectionCount = 0;
    }
   
    private void Print(){
            DefaultListModel report = new DefaultListModel();
            for(int x = 0; x<inspectionCount; x++){
                        report = createReport(inspections[x][0], inspections[x][1], inspections[x][2], report);
            }
           this.details_List.setModel(report);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name_label = new javax.swing.JLabel();
        location_Label = new javax.swing.JLabel();
        year_Label = new javax.swing.JLabel();
        name_TextField = new javax.swing.JTextField();
        location_TextField = new javax.swing.JTextField();
        year_ComboBox = new javax.swing.JComboBox<>();
        save_Button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        details_List = new javax.swing.JList<>();
        print_Button = new javax.swing.JButton();
        clear_Button = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        file_Menu = new javax.swing.JMenu();
        tools_Menu = new javax.swing.JMenu();
        save_Menu = new javax.swing.JMenuItem();
        print_Menu = new javax.swing.JMenuItem();
        clear_Menu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital Inspections");

        name_label.setText("Hospital Name:");

        location_Label.setText("Hospital Location:");

        year_Label.setText("Years since Inspection:");

        year_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Years", "2 Years", "3 Years", "4 Years", "5 Years" }));

        save_Button.setText("Save");
        save_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_ButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(details_List);

        print_Button.setText("Print");
        print_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_ButtonActionPerformed(evt);
            }
        });

        clear_Button.setText("Clear");
        clear_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_ButtonActionPerformed(evt);
            }
        });

        file_Menu.setText("File");
        jMenuBar1.add(file_Menu);

        tools_Menu.setText("Tools");

        save_Menu.setText("Save");
        save_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_MenuActionPerformed(evt);
            }
        });
        tools_Menu.add(save_Menu);

        print_Menu.setText("Print");
        print_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_MenuActionPerformed(evt);
            }
        });
        tools_Menu.add(print_Menu);

        clear_Menu.setText("Clear");
        clear_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_MenuActionPerformed(evt);
            }
        });
        tools_Menu.add(clear_Menu);

        jMenuBar1.add(tools_Menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(year_Label)
                            .addComponent(location_Label)
                            .addComponent(name_label))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(save_Button)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(name_TextField)
                                .addComponent(location_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                            .addComponent(year_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(print_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clear_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_label)
                    .addComponent(name_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(location_Label)
                    .addComponent(location_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(year_Label)
                    .addComponent(year_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(save_Button)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(print_Button)
                    .addComponent(clear_Button))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void save_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_ButtonActionPerformed
      Save();
    }//GEN-LAST:event_save_ButtonActionPerformed

    private void print_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_ButtonActionPerformed
        Print();
    }//GEN-LAST:event_print_ButtonActionPerformed

    private void clear_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_ButtonActionPerformed
      Clear();
    }//GEN-LAST:event_clear_ButtonActionPerformed

    private void save_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_MenuActionPerformed
      Save();
    }//GEN-LAST:event_save_MenuActionPerformed

    private void print_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_MenuActionPerformed
        Print();
    }//GEN-LAST:event_print_MenuActionPerformed

    private void clear_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_MenuActionPerformed
        Clear();
    }//GEN-LAST:event_clear_MenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hospital_GUI_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hospital_GUI_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hospital_GUI_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hospital_GUI_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hospital_GUI_App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear_Button;
    private javax.swing.JMenuItem clear_Menu;
    private javax.swing.JList<String> details_List;
    private javax.swing.JMenu file_Menu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel location_Label;
    private javax.swing.JTextField location_TextField;
    private javax.swing.JTextField name_TextField;
    private javax.swing.JLabel name_label;
    private javax.swing.JButton print_Button;
    private javax.swing.JMenuItem print_Menu;
    private javax.swing.JButton save_Button;
    private javax.swing.JMenuItem save_Menu;
    private javax.swing.JMenu tools_Menu;
    private javax.swing.JComboBox<String> year_ComboBox;
    private javax.swing.JLabel year_Label;
    // End of variables declaration//GEN-END:variables
}
